CREATE TABLE IF NOT EXISTS users(
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    userid SERIAL PRIMARY KEY,
    email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS flags(
    userid INT PRIMARY KEY REFERENCES users ON DELETE CASCADE,
    todo BOOLEAN DEFAULT FALSE,
    hoursrange numrange DEFAULT numrange('[14, 22]')
);

CREATE TABLE IF NOT EXISTS words(
    userid INT PRIMARY KEY REFERENCES users ON DELETE CASCADE,
    list JSON NOT NULL DEFAULT '[]'
);