"""empty message

Revision ID: 3e9d8fbe4d52
Revises: aafd21881fd9
Create Date: 2024-01-11 19:17:04.779112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9d8fbe4d52'
down_revision = 'aafd21881fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.alter_column('instaling_user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('instaling_pass',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.alter_column('instaling_pass',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('instaling_user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
