"""empty message

Revision ID: 4d7ff8141741
Revises: c3fc0da0098b
Create Date: 2024-01-11 22:45:39.452465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d7ff8141741'
down_revision = 'c3fc0da0098b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.alter_column('todo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hoursrange',
               existing_type=postgresql.NUMRANGE(),
               nullable=False)

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # Manually update existing rows with the default value
    op.execute("UPDATE words SET active = FALSE WHERE active IS NULL")

    # Alter the column to make it not nullable
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('active', nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.alter_column('hoursrange',
               existing_type=postgresql.NUMRANGE(),
               nullable=True)
        batch_op.alter_column('todo',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
