"""empty message

Revision ID: a149fe7d804b
Revises: 
Create Date: 2024-01-09 22:47:37.115650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a149fe7d804b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('flags',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('todo', sa.Boolean(), nullable=True),
    sa.Column('hoursrange', postgresql.NUMRANGE(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('words',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('list', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('flags')
    op.drop_table('users')
    # ### end Alembic commands ###
