"""empty message

Revision ID: aafd21881fd9
Revises: a149fe7d804b
Create Date: 2024-01-11 19:14:42.136229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafd21881fd9'
down_revision = 'a149fe7d804b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_bot_version')
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instaling_user', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instaling_pass', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.drop_column('instaling_pass')
        batch_op.drop_column('instaling_user')

    op.create_table('alembic_bot_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_bot_version_pkc')
    )
    # ### end Alembic commands ###
