"""empty message

Revision ID: c3fc0da0098b
Revises: 
Create Date: 2024-01-11 22:26:34.124992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fc0da0098b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        # Add the column as nullable initially
        batch_op.add_column(sa.Column('error_level', sa.Integer(), nullable=True))

    # Manually update existing rows with the default value
    op.execute("UPDATE flags SET error_level = 5 WHERE error_level IS NULL")

    # Alter the column to make it not nullable
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.alter_column('error_level', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.drop_column('error_level')

    # ### end Alembic commands ###
